apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-nginx
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }} 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: {{ .Release.Name }}-nginx-configmap