apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
annotations:
  "helm.sh/hook": post-install
  "helm.sh/hook-weight": "-5"
  "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-post-install
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "busybox"
        command: ['/bin/echo']
        args: ['I am done with cleanup!']